config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers

root 'customers#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :customer
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :customers
  /複数形であることに注意/
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :company

  # company_idの以下の２行を追加
  validates :company_id, presence: true,
    length: { maximum: 20 }
  validates :family_name, presence: true,
    length: { maximum: 20 }
  validates :given_name, presence: true,
    length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  def full_name
    full_name = family_name  + given_name + '様'
    return full_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    full_name = family_name  + given_name
    return full_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # strong parameterみたいなもの
    devise_parameter_sanitizer.for(:sign_up) << :family_name
    devise_parameter_sanitizer.for(:sign_up) << :given_name
    devise_parameter_sanitizer.for(:account_update)<< :family_name
    devise_parameter_sanitizer.for(:account_update) << :given_name

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  # 〜以外という場合はonlyの代わりにexceptをはめる
  before_action :set_company, only: [:new, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @customers = Customer.page(params[:page])
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      # true
      redirect_to @customer
    else
      #false
      render :new
    end
  end

  def update
    # validationの組み込み
    if
      redirect_to @customer
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @customer.destroy
    redirect_to customer_url
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end
    def set_company
      @companies = Company.all
    end
    def customer_params
      params.require(:customer).permit( :family_name, :given_name, :email, :company_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>

<!--  company_id とpostについてf.collection_selectで編集できるようにする -->

  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>
​
      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :company_id %><br />
  <%= f.collection_select :company_id, Company.all, :id, :name %>
</div>

</div>
<div class="form-group">
  <%= f.label :family_name %><br />
  <%= f.text_field :family_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :given_name %><br/ >
  <%= f.text_field :given_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %><br />
  <%= f.text_field :email, class: 'form-control' %>
</div>

<%= f.submit %>

<% end %>

app/views/customers/edit.html.erb
<h1>顧客編集</h1>
<%= render partial: 'form' %>
<button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
<div class="modal fade" id="delete-customer">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title">顧客情報の削除</h4>
     </div>
     <div class="modal-body">
       <p><%= @customer.family_name %>さんを削除しますか？</p>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
       <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
     </div>
   </div>
 </div>
</div>

app/views/customers/index.html.erb
<h1>顧客情報一覧</h1>
<p>お客様情報が表示されます。</p>
<table class="table table-striped">
  <thead>
    <th>会社名</th>
    <th>姓</th>
    <th>名</th>
    <th>電子メール</th>
    <th>リンク</th>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.company.name %></td>
        <!--  役職について追加 -->
        <td><%= customer.family_name %></td>
        <td><%= customer.given_name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @customers %>

app/views/customers/new.html.erb
<h1>顧客新規登録</h1>
<%= render partial: 'form' %>

app/views/customers/show.html.erb
<div class = "row">
  <div class = "col-md-12">
    <dl>

      <!-- ここから -->
      <dt>会社名</dt>
      <dd><%= @customer.company_id %> </dd>
      <!--  ここまで追加 -->

      <dt>名前</dt>
      <dd><%= @customer.full_name %> </dd>
      <dt>電子メール</dt>
      <dd><%= @customer.email %></dd>
    </dl>
  </div>

  <!-- 以下の２行を追加-->
<%= link_to '編集する', edit_customer_path(@customer.id) %>
<%= link_to '削除する', customer_path(@customer.id), method: :delete %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">

        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>

        <% if user_signed_in? %>
       <p class="navbar-text navbar-right">
       <%=  current_user.full_name %>さんでログイン中</p>
     <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>

<%= render partial: 'layouts/header' %>

<div class="container">

<% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>